#!/bin/bash

#local of the ping log file:
log=/tmp/pinger.log

#file with stats:
stats=/tmp/stats.log

if [ "$#" -lt 1 ]; then
	echo "No arguments, please add the times to be monitored."
	exit 0
fi

#Clean lines by double the last amount.
clear_lines=$(echo "${@: -1} * 2"|bc)

> $stats
for var in "$@"
do
	value=$(tail -n $var $log|grep -c "^$"|xargs -i echo "({}/$var) * 100"|bc -l|sed 's/..................$//')
	if [ "$var" -lt "60" ]; then
		echo "${var}s: $value%" >> $stats
	else
		time=$(( $var / 60 ))
		echo "${time}m: $value%" >> $stats
	fi
done
echo $(cat $stats|tr "\n" " ")
t_lines=$(cat $log|wc -l)
if [ $t_lines -gt $clear_lines ]; then
	#clear the first ${@: -1} lines
	sed -i 1,${@: -1}d $log
fi
exit 0
